version: "2"
networks:
  spark:
    driver: bridge
services:
  master:
    image: gettyimages/spark:2.0.0-hadoop-2.7
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    environment:
      MASTER: spark://master:7077
      SPARK_PUBLIC_DNS: localhost
      SPARK_MASTER_WEBUI_PORT: 4040
      SPARK_MASTER_OPTS: >-
        -Dspark.fileserver.port=7002
        -Dspark.broadcast.port=7003
        -Dspark.replClassServer.port=7004
        -Dspark.blockManager.port=7005
        -Dspark.executor.port=7006
        -Dspark.port.maxRetries=4
    networks: [spark]
    expose:
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077

  worker:
    image: gettyimages/spark:2.0.0-hadoop-2.7
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_WEBUI_PORT: 4041
      SPARK_WORKER_PORT: 17000
      SPARK_PUBLIC_DNS: localhost
      SPARK_WORKER_OPTS: >-
        -Dspark.fileserver.port=17002
        -Dspark.broadcast.port=17003
        -Dspark.replClassServer.port=17004
        -Dspark.blockManager.port=17005
        -Dspark.executor.port=17006
        -Dspark.port.maxRetries=4
    networks: [spark]
    expose:
      - 17000
      - 17002
      - 17003
      - 17004
      - 17005
      - 17006
    ports:
      - 4041:4041
    volumes:
      - ../geo:/var/lib/geo
      - ../data:/var/lib/data

  elasticsearch:
    image: elasticsearch:2.3
    networks: [spark]
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:4.5
    networks: [spark]
    ports:
      - 5601:5601
    logging:
      driver: none
